var annotated =
[
    [ "Chart", null, [
      [ "Function", "struct_chart_1_1_function.html", "struct_chart_1_1_function" ],
      [ "PointMagnitude", "struct_chart_1_1_point_magnitude.html", "struct_chart_1_1_point_magnitude" ],
      [ "NumericField", "struct_chart_1_1_numeric_field.html", "struct_chart_1_1_numeric_field" ]
    ] ],
    [ "Gameplay", "namespace_gameplay.html", "namespace_gameplay" ],
    [ "Geometry2d", null, [
      [ "Circle", "class_geometry2d_1_1_circle.html", "class_geometry2d_1_1_circle" ],
      [ "Line", "class_geometry2d_1_1_line.html", "class_geometry2d_1_1_line" ],
      [ "Point", "class_geometry2d_1_1_point.html", "class_geometry2d_1_1_point" ],
      [ "Polygon", "class_geometry2d_1_1_polygon.html", "class_geometry2d_1_1_polygon" ],
      [ "Pose", "class_geometry2d_1_1_pose.html", "class_geometry2d_1_1_pose" ],
      [ "Rect", "class_geometry2d_1_1_rect.html", "class_geometry2d_1_1_rect" ],
      [ "Segment", "class_geometry2d_1_1_segment.html", "class_geometry2d_1_1_segment" ],
      [ "TransformMatrix", "class_geometry2d_1_1_transform_matrix.html", "class_geometry2d_1_1_transform_matrix" ]
    ] ],
    [ "LinAlg", "namespace_lin_alg.html", null ],
    [ "Planning", "namespace_planning.html", "namespace_planning" ],
    [ "AutoName", "class_auto_name.html", "class_auto_name" ],
    [ "Ball", "class_ball.html", "class_ball" ],
    [ "BallFilter", "class_ball_filter.html", "class_ball_filter" ],
    [ "BallObservation", "class_ball_observation.html", "class_ball_observation" ],
    [ "BallTracker", "class_ball_tracker.html", "class_ball_tracker" ],
    [ "CircleObstacle", "class_circle_obstacle.html", "class_circle_obstacle" ],
    [ "ConfigBool", "class_config_bool.html", "class_config_bool" ],
    [ "ConfigDouble", "class_config_double.html", "class_config_double" ],
    [ "ConfigInt", "class_config_int.html", "class_config_int" ],
    [ "ConfigItem", "class_config_item.html", "class_config_item" ],
    [ "Configurable", "class_configurable.html", "class_configurable" ],
    [ "ConfigurableImpl", "class_configurable_impl.html", "class_configurable_impl" ],
    [ "Configuration", "class_configuration.html", "class_configuration" ],
    [ "ExceptionIterator", "class_exception_iterator.html", "class_exception_iterator" ],
    [ "FaceTarget", "class_face_target.html", "class_face_target" ],
    [ "FieldView", "class_field_view.html", "class_field_view" ],
    [ "FIRFilter", "class_f_i_r_filter.html", "class_f_i_r_filter" ],
    [ "GameState", "class_game_state.html", "class_game_state" ],
    [ "Joystick", "class_joystick.html", "class_joystick" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "LogViewer", "class_log_viewer.html", "class_log_viewer" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "MotionCommand", "class_motion_command.html", "class_motion_command" ],
    [ "MotionControl", "class_motion_control.html", "class_motion_control" ],
    [ "MotionTarget", "class_motion_target.html", "class_motion_target" ],
    [ "Obstacle", "class_obstacle.html", "class_obstacle" ],
    [ "ObstacleGroup", "class_obstacle_group.html", "class_obstacle_group" ],
    [ "OpponentRobot", "class_opponent_robot.html", "class_opponent_robot" ],
    [ "OurRobot", "class_our_robot.html", "class_our_robot" ],
    [ "Pid", "class_pid.html", "class_pid" ],
    [ "PlayConfigTab", "class_play_config_tab.html", "class_play_config_tab" ],
    [ "PolygonObstacle", "class_polygon_obstacle.html", "class_polygon_obstacle" ],
    [ "Processor", "class_processor.html", "class_processor" ],
    [ "ProtobufTree", "class_protobuf_tree.html", "class_protobuf_tree" ],
    [ "QuaternionDemo", "class_quaternion_demo.html", "class_quaternion_demo" ],
    [ "Radio", "class_radio.html", "class_radio" ],
    [ "RefereeModule", "class_referee_module.html", "class_referee_module" ],
    [ "RefereeTab", "class_referee_tab.html", "class_referee_tab" ],
    [ "Robot", "class_robot.html", "class_robot" ],
    [ "RobotConfig", "class_robot_config.html", "class_robot_config" ],
    [ "RobotFilter", "class_robot_filter.html", "class_robot_filter" ],
    [ "RobotObservation", "class_robot_observation.html", "class_robot_observation" ],
    [ "RobotPose", "class_robot_pose.html", "class_robot_pose" ],
    [ "RobotStatus", "class_robot_status.html", "class_robot_status" ],
    [ "SimFieldView", "class_sim_field_view.html", "class_sim_field_view" ],
    [ "SimRadio", "class_sim_radio.html", "class_sim_radio" ],
    [ "StripChart", "class_strip_chart.html", "class_strip_chart" ],
    [ "SystemState", "class_system_state.html", "class_system_state" ],
    [ "Timeout", "class_timeout.html", "class_timeout" ],
    [ "USBRadio", "class_u_s_b_radio.html", "class_u_s_b_radio" ],
    [ "VisionPacket", "class_vision_packet.html", "class_vision_packet" ],
    [ "VisionReceiver", "class_vision_receiver.html", "class_vision_receiver" ]
];